DELETE https://wall-e.servicebus.windows.net/commands/messages/head?timeout=60&api-version=2015-01
Accept: application/json
Authorization: SharedAccessSignature sr=https%3A%2F%2FWALL-E.servicebus.windows.net%2Ftelemetry&sig=pQXlJ7uBSyBDHE2Aa5PFDrU71M%2BLVrwLnuWkeg3kvYs%3D&se=1519894747&skn=SendListen
###

POST https://wall-e.servicebus.windows.net/commands/messages?api-version=2015-01
Content-Type: application/json
Accept: application/json
Authorization: SharedAccessSignature sr=https%3A%2F%2FWALL-E.servicebus.windows.net%2Ftelemetry&sig=pQXlJ7uBSyBDHE2Aa5PFDrU71M%2BLVrwLnuWkeg3kvYs%3D&se=1519894747&skn=SendListen

{
    "Event": "MyTest"
}
###

GET https://wall-e.servicebus.windows.net/commands/messages?timeout=60&api-version=2015-01
Accept: application/json
Authorization: SharedAccessSignature sr=https%3A%2F%2FWALL-E.servicebus.windows.net%2Ftelemetry&sig=pQXlJ7uBSyBDHE2Aa5PFDrU71M%2BLVrwLnuWkeg3kvYs%3D&se=1519894747&skn=SendListen
###

## curl -X POST https://ultraawesome.servicebus.windows.net/awesomequeue/messages -H "Authorization: SharedAccessSignature sr=https%3a%2f%2fultraawesome.servicebus.windows.net%2fawesomequeue%2f&sig=WuIKwkBuB%2fjxMgK6x79o3Xrf4nKZtWX9defu7HLdzWg%3d&se=1422636195&skn=Send" -H "Conent-Type:application/json" -d "I am a message"




POST https://WALL-E.servicebus.windows.net/telemetry/messages
Content-Type: application/json
Accept: application/json
Authorization: SharedAccessSignature sr=https%3a%2f%2fWALL-E.servicebus.windows.net%2f&sig=xQ1Lwu7wghlwPUcP3fVEPAjdgHJkY9YkI6iAe1W2IZs%3d&se=1828442932&skn=Rover

{
    "Content": "MyTestTopic"
}
###


DELETE https://WALL-E.servicebus.windows.net/telemetry/subscriptions/monitoring/messages/head/?api-version=2015-01
Accept: application/json
Authorization: SharedAccessSignature sr=https%3A%2F%2FWALL-E.servicebus.windows.net%2Ftelemetry&sig=lIkVBsRHTDkdJWNC7lci4tjR5Irge4As6i4jjvUY8eQ%3D&se=1520421274&skn=SendListen
###